hyperparameters:
  # Training Parameters
  episode_length: 10 # Number of timesteps per episode
  log_freq: 5 # How often tensorboard is updated (Tensorboard appears to only log evals)
  total_timesteps: 10000 # Number of timesteps to train on
  eval_frequency: 50 # How many timesteps before evaluating
  checkpoint_frequency: 0 # How often a checkpoint model is saved

  # Robot parameters
  step_size: 0.04 # How many units the end effector moves each step
