left:
  pose/preHandoff:
    position:
      x: 0.1
      y: -0.4
      z: 0.3
    orientation:
      x: 0.5
      y: 0.5
      z: 0.5
      w: 0.5

  pose/handoff:
    position:
      x: 0.19
      y: -0.4
      z: 0.3
    orientation:
      x: 0.5
      y: 0.5
      z: 0.5
      w: 0.5

  pose/pickup:
    position:
      x: -0.3
      y: -0.1
      z: 0.10
    orientation:
      x: -0.999911
      y: 0.006463
      z: -0.007255
      w: -0.009191

  pose/preGrasp:
    position:
      x: -0.3
      y: -0.1
      z: 0.4
    orientation:
      x: -0.999911
      y: 0.006463
      z: -0.007255
      w: -0.009191

  pose/postGrasp:
    position:
      x: -0.25677
      y: -0.0545
      z: 0.25
    orientation:
      x: -0.999911
      y: 0.006463
      z: -0.007255
      w: -0.009191
      


right:
  pose/preHandoff:
    position:
      x: 0.38
      y: -0.4
      z: 0.35
    orientation:
      x: 0.5
      y: -0.5
      z: -0.5
      w: 0.5

  pose/handoff:
    position:
      x: 0.28
      y: -0.4
      z: 0.35
    orientation:
      x: 0.5
      y: -0.5
      z: -0.5
      w: 0.5

  pose/pickup:
    position:
      x: 0.834
      y: -0.034
      z: 0.15
    orientation:
      x: 0.679
      y: -0.733
      z: -0.042
      w: 0.033

gripper:
  open:
    -0.523
  close:
    0.785398
