controller_list:
  - name: fake_ar3_arm_controller
    type: $(arg execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: fake_end_effector_controller
    type: $(arg execution_type)
    joints:
      - joint_6
initial:  # Define initial robot poses.
  - group: ar3_arm
    pose: extended
  - group: end_effector
    pose: home